version: "3.9"

services:
  db:
    restart: always
    #network_mode: satbnet
    networks:
      - satbnet
    image: postgres:latest
    volumes:
      - postgres_db:/var/lib/postgresql/data
      - ./postgres_config:/var/lib/postgresql/config
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"

  web:
    #network_mode: satbnet
    networks:
      - satbnet
    build: .
    volumes:
      - .:/code
    command: python pjtsite/manage.py runserver 0.0.0.0:8000

    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    links:
      - db:db
    depends_on:
      - db
networks:
  satbnet:
    driver: bridge
volumes:
  postgres_db:
    external: true
