# Generated by Django 3.2.13 on 2022-05-13 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OrderID', models.CharField(max_length=32)),
                ('ItemSKU', models.CharField(max_length=48)),
                ('OrderQuantity', models.CharField(max_length=12)),
            ],
        ),
    ]
