# Generated by Django 3.2.13 on 2024-01-25 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OrderQuantity', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('OrdersID', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('FullName', models.CharField(max_length=48)),
                ('FirstName', models.CharField(max_length=48)),
                ('LastName', models.CharField(max_length=48)),
                ('SaleDate', models.DateField()),
                ('RequiredShipDate', models.DateField()),
                ('OrderPlatform', models.CharField(max_length=32)),
                ('OrderCompleted', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='PrintFileData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FileName', models.CharField(max_length=128)),
                ('Scope', models.CharField(max_length=48)),
                ('Printer', models.CharField(max_length=48)),
                ('Color', models.CharField(max_length=48)),
                ('FileWeight', models.IntegerField()),
                ('FileTime', models.DecimalField(decimal_places=2, max_digits=48)),
                ('PrintQuantity', models.IntegerField()),
                ('PrintWeight', models.IntegerField()),
                ('PrintTime', models.DecimalField(decimal_places=2, max_digits=48)),
            ],
        ),
        migrations.CreateModel(
            name='PrintFileStates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StateName', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='PrintModels',
            fields=[
                ('ModelSKU', models.CharField(max_length=24, primary_key=True, serialize=False, unique=True)),
                ('ModelName', models.CharField(max_length=150)),
                ('BoardGame', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PrintFileStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ItemSKU', models.CharField(max_length=25)),
                ('OrderQuantityCompleted', models.IntegerField()),
                ('PrintFileCompleted', models.BooleanField()),
                ('tblOrderItems_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pjtapp.orderitems')),
                ('tblPrintFileData_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='pjtapp.printfiledata')),
            ],
        ),
        migrations.CreateModel(
            name='PrintFileStateHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StatusSetDate', models.DateField()),
                ('StatusSetTime', models.TimeField()),
                ('NewStateName', models.CharField(max_length=15)),
                ('PrintFileStatusID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pjtapp.printfilestatus')),
            ],
        ),
        migrations.AddField(
            model_name='printfiledata',
            name='ParentSKU',
            field=models.ForeignKey(db_column='ParentSKU', on_delete=django.db.models.deletion.CASCADE, to='pjtapp.printmodels'),
        ),
        migrations.AddField(
            model_name='orderitems',
            name='ItemSKU',
            field=models.ForeignKey(db_column='ItemSKU', on_delete=django.db.models.deletion.CASCADE, to='pjtapp.printmodels'),
        ),
        migrations.AddField(
            model_name='orderitems',
            name='OrdersID',
            field=models.ForeignKey(db_column='OrdersID', on_delete=django.db.models.deletion.CASCADE, to='pjtapp.orders'),
        ),
    ]
