# Generated by Django 3.2.13 on 2022-06-28 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pjtapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='OrdersID',
            field=models.BigIntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
