# Generated by Django 3.2.13 on 2022-05-25 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pjtapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OrderID', models.CharField(max_length=32)),
                ('FullName', models.CharField(max_length=48)),
                ('FirstName', models.CharField(max_length=48)),
                ('LastName', models.CharField(max_length=48)),
                ('SaleDate', models.DateField()),
                ('RequiredShipDate', models.DateField()),
                ('OrderPlatform', models.CharField(max_length=32)),
                ('OrderCompleted', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='PrintFileData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SKU', models.CharField(max_length=32)),
                ('FileName', models.CharField(max_length=128)),
                ('Scope', models.CharField(max_length=48)),
                ('Printer', models.CharField(max_length=48)),
                ('Color', models.CharField(max_length=48)),
                ('FileWeight', models.IntegerField()),
                ('FileTime', models.DecimalField(decimal_places=2, max_digits=5)),
                ('PrintQuantity', models.IntegerField()),
                ('PrintWeight', models.IntegerField()),
                ('PrintTime', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='PrintFileStateHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PrintFileStateHistoryID', models.IntegerField()),
                ('PrintFileStatusID', models.IntegerField()),
                ('StatusSetDate', models.DateField()),
                ('StatusSetTime', models.TimeField()),
                ('NewStateName', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='PrintFileStates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PrintFileStatesID', models.IntegerField()),
                ('StateName', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='PrintFileStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PrintFileStatusID', models.IntegerField()),
                ('OrderItemsID', models.IntegerField()),
                ('ItemSKU', models.CharField(max_length=25)),
                ('PrintFileID', models.IntegerField()),
                ('OrderQuantityCompleted', models.IntegerField()),
                ('PrintFileCompleted', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='PrintModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ModelSkU', models.CharField(max_length=32)),
                ('ModelName', models.CharField(max_length=150)),
                ('BoardGame', models.CharField(max_length=40)),
            ],
        ),
    ]
