# Generated by Django 3.2.13 on 2023-06-07 03:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pjtapp', '0002_auto_20221025_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printfilestatus',
            name='tblPrintFileData_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='pjtapp.printfiledata'),
        ),
    ]
