create table postgres.public.tblPrintFileData 
(
	PrintFileDataID int generated by default as IDENTITY primary KEY,
	ParentSKU varchar(25),
	PrintFileName varchar(80),
	PrintType varchar(20),
	Printer varchar(20),
	PrintColor varchar(40),
	FileWeight float(8),
	FileTime float(8),
	PrintQuantity int,
	PrintWeight float(8),
	PrintTime float(8)
);

create table postgres.public.tblPrintModels
(
	ModelSKU varchar(25),
	ModelName varchar(150),
	BoardGame varchar(40)
);

create table postgres.public.tblOrderItems
(
	OrderItemsID int generated by default as IDENTITY primary KEY,
	OrdersID float(8),
	ItemSKU varchar(25),
	OrderQuantity int,
	QuantityCompleted int
);

create table postgres.public.tblOrders
(
	OrderID bigint generated by default as identity primary key,
	FullName varchar(60),
	FirstName varchar(30),
	LastName varchar(30),
	OrderDate date,
	RequiredShipDate date,
	OrderPlatform varchar(10)
);

create table postgres.public.tblPrintFileStatus
(
	PrintFileStatusID int generated by default as identity primary key,
	OrderItemsID int,
	ItemSKU varchar(25),
	PrintFileID int,
	OrderQuantityCompleted int,
	PrintFileCompleted boolean
);
create table postgres.public.tblPrintFileStateHistory
(
	PrintfileStateHistoryID int generated by default as identity primary key,
	PrintFileStatusID int,
	StatusSetDate date,
	StatusSetTime time,
	NewStateName varchar(15)
);

create table postgres.public.tblPrintFileStates
(
	PrintFileStatesID int generated by default as identity primary key,
	StateName varchar(15)
);